export const packingLists = {
  hikingRain: [
    "T-Shirt x 3",
    "Exercise Shirt x 3",
    "Polo x 0",
    "Long-Slvd Shirt x 2",
    "Sun-Shirt x 1",
    "Dress Shirt x 0",
    "Under Shirt x 0",
    "Pajama Shirt x 1",
    "Jacket x 1",
    "Rain Jacket x 1",
    "Suit Jacket x 0",
    "Ski Jacket x 0",
    "Tie x 0",
    "Mask x 1",
    "Bandana x 7",
    "Head Band x 1",
    "Regular Belt x 1",
    "Dress Belt x 0",
    "Hiking Belt x 1",
    "Shorts x 1",
    "Gym Shorts x 1",
    "Swimsuit x 1",
    "Hiking Pants x 2",
    "Jeans x 3",
    "Dress Pants x 0",
    "Pajama Pants x 1",
    "Pajama Shorts x 0",
    "Waterproof Pants x 1",
    "Ski Pants x 0",
    "Briefs x 8",
    "Winter Undrwear x 0",
    "Short Socks x 3",
    "Long Socks x 4",
    "Winter Socks x 4",
    "Snapback x 1",
    "Trail Hat x 1",
    "Beanie x 0",
    "Snow Gloves x 0",
    "Reg Gloves x 1",
    "Scarf x 0",
    "Sneakers x 1",
    "Waterproof Boots x 1",
    "Reg Hiking Boots x 0",
    "Dress Shoes x 0",
    "Water Shoes x 1",
    "Sandals x 0",
    "Reg-Glasses x 1",
    "Sunglasses x 1",
    "Lense Cleaner x 1",
    "Eye Drops x 1",
    "Toothpaste x 1",
    "Toothbrush x 1",
    "Floss Sticks x 10",
    "Meds x 1",
    "Inhaler x 1",
    "vitamins x 1",
    "Sunscreen x 1",
    "Lotion x 1",
    "Hand Sanitizer x 1",
    "Clorox Trvl x 1",
    "Body Wash x 1",
    "Shampoo x 1",
    "Face Cleaner x 1",
    "Chapstick x 2",
    "Comb x 1",
    "Hair Putty x 0",
    "Deodorant x 1",
    "Shaving Kit x 0",
    "Tissues x 3",
    "Lint Roller x 0",
    "Shoe Shine x 0",
    "Bug Spray x 1",
    "Talcum Powder x 2",
    "Misc BR Items x 1",
    "Travel Towel x 1",
    "Travel Pillow x 1",
    "Hiking Bag x 1",
    "Sling Bag x 0",
    "Laundry Bag x 1",
    "Rain Covers x 2",
    "Laptop & gear x 0",
    "Phone Charger x 1",
    "Charge Cord x 1",
    "Travel Btry Sm x 1",
    "Travel Btry Lrg x 0",
    "Wireless Buds x 1",
    "Switch & gear x 0",
    "Extension Cord x 1",
    "Gum x 1",
    "Snacks x 6",
    "Empty Bottle x 1",
    "Lifting Wraps x 0",
    "Wallet x 1",
    "Keys x 1",
    "Passport x 0",
    "Silicone Ring x 1",
    "Ring x 0",
    "Ring Bandit x 1",
    "Emgcy Cash x 200",
    "Notepad & Pen x 1",
    "Sharpie x 1",
    "H2O Proof Pouch x 1",
    "Rmv Swiss Knife x 1",
    "First Aid Kit x 1",
    "MTG Cards x 0",
    "MTG Playmat x 0",
    "Counters & Dice x 0",
  ],
  hikingCold: [
    "T-Shirt x 3",
    "Exercise Shirt x 0",
    "Polo x 0",
    "Long-Slvd Shirt x 3",
    "Sun-Shirt x 1",
    "Dress Shirt x 0",
    "Under Shirt x 1",
    "Pajama Shirt x 1",
    "Jacket x 1",
    "Rain Jacket x 1",
    "Suit Jacket x 0",
    "Ski Jacket x 0",
    "Tie x 0",
    "Mask x 1",
    "Bandana x 3",
    "Head Band x 0",
    "Regular Belt x 1",
    "Dress Belt x 0",
    "Hiking Belt x 1",
    "Shorts x 0",
    "Gym Shorts x 0",
    "Swimsuit x 1",
    "Hiking Pants x 2",
    "Jeans x 1",
    "Dress Pants x 0",
    "Pajama Pants x 1",
    "Pajama Shorts x 0",
    "Waterproof Pants x 1",
    "Ski Pants x 0",
    "Briefs x 7",
    "Winter Undrwear x 1",
    "Short Socks x 2",
    "Long Socks x 3",
    "Winter Socks x 3",
    "Snapback x 1",
    "Trail Hat x 1",
    "Beanie x 1",
    "Snow Gloves x 1",
    "Reg Gloves x 1",
    "Scarf x 1",
    "Sneakers x 1",
    "Waterproof Boots x 1",
    "Reg Hiking Boots x 0",
    "Dress Shoes x 0",
    "Water Shoes x 0",
    "Sandals x 0",
    "Reg-Glasses x 1",
    "Sunglasses x 1",
    "Lense Cleaner x 1",
    "Eye Drops x 1",
    "Toothpaste x 1",
    "Toothbrush x 1",
    "Floss Sticks x 10",
    "Meds x 1",
    "Inhaler x 1",
    "vitamins x 1",
    "Sunscreen x 1",
    "Lotion x 1",
    "Hand Sanitizer x 1",
    "Clorox Trvl x 1",
    "Body Wash x 1",
    "Shampoo x 1",
    "Face Cleaner x 1",
    "Chapstick x 2",
    "Comb x 1",
    "Hair Putty x 0",
    "Deodorant x 1",
    "Shaving Kit x 0",
    "Tissues x 2",
    "Lint Roller x 0",
    "Shoe Shine x 0",
    "Bug Spray x 0",
    "Talcum Powder x 1",
    "Misc BR Items x 1",
    "Travel Towel x 1",
    "Travel Pillow x 1",
    "Hiking Bag x 1",
    "Sling Bag x 0",
    "Laundry Bag x 1",
    "Rain Covers x 2",
    "Laptop & gear x 0",
    "Phone Charger x 1",
    "Charge Cord x 1",
    "Travel Btry Sm x 1",
    "Travel Btry Lrg x 0",
    "Wireless Buds x 1",
    "Switch & gear x 0",
    "Extension Cord x 1",
    "Gum x 1",
    "Snacks x 8",
    "Empty Bottle x 1",
    "Lifting Wraps x 0",
    "Wallet x 1",
    "Keys x 1",
    "Passport x 0",
    "Silicone Ring x 1",
    "Ring x 0",
    "Ring Bandit x 1",
    "Emgcy Cash x 200",
    "Notepad & Pen x 1",
    "Sharpie x 1",
    "H2O Proof Pouch x 1",
    "Rmv Swiss Knife x 1",
    "First Aid Kit x 1",
    "MTG Cards x 0",
    "MTG Playmat x 0",
    "Counters & Dice x 0",
  ],
  fancy: [
    "T-Shirt x 3",
        "Exercise Shirt x 2",
        "Polo x 2",
        "Long-Slvd Shirt x 2",
        "Sun-Shirt x 0",
        "Dress Shirt x 2",
        "Under Shirt x 2",
        "Pajama Shirt x 1",
        "Jacket x 1",
        "Rain Jacket x 0",
        "Suit Jacket x 1",
        "Ski Jacket x 0",
        "Tie x 1",
        "Mask x 1",
        "Bandana x 4",
        "Head Band x 1",
        "Regular Belt x 1",
        "Dress Belt x 1",
        "Hiking Belt x 0",
        "Shorts x 2",
        "Gym Shorts x 2",
        "Swimsuit x 0",
        "Hiking Pants x 0",
        "Jeans x 2",
        "Dress Pants x 2",
        "Pajama Pants x 0",
        "Pajama Shorts x 1",
        "Waterproof Pants x 0",
        "Ski Pants x 0",
        "Briefs x 7",
        "Winter Undrwear x 0",
        "Short Socks x 4",
        "Long Socks x 4",
        "Winter Socks x 0",
        "Snapback x 1",
        "Trail Hat x 0",
        "Beanie x 0",
        "Snow Gloves x 0",
        "Reg Gloves x 0",
        "Scarf x 0",
        "Sneakers x 1",
        "Waterproof Boots x 0",
        "Reg Hiking Boots x 0",
        "Dress Shoes x 1",
        "Water Shoes x 0",
        "Sandals x 0",
        "Reg-Glasses x 1",
        "Sunglasses x 1",
        "Lense Cleaner x 1",
        "Eye Drops x 1",
        "Toothpaste x 1",
        "Toothbrush x 1",
        "Floss Sticks x 10",
        "Meds x 1",
        "Inhaler x 1",
        "vitamins x 1",
        "Sunscreen x 1",
        "Lotion x 1",
        "Hand Sanitizer x 1",
        "Clorox Trvl x 1",
        "Body Wash x 1",
        "Shampoo x 1",
        "Face Cleaner x 1",
        "Chapstick x 2",
        "Comb x 1",
        "Hair Putty x 1",
        "Deodorant x 1",
        "Shaving Kit x 1",
        "Tissues x 2",
        "Lint Roller x 1",
        "Shoe Shine x 1",
        "Bug Spray x 1",
        "Talcum Powder x 1",
        "Misc BR Items x 1",
        "Travel Towel x 0",
        "Travel Pillow x 1",
        "Hiking Bag x 0",
        "Sling Bag x 1",
        "Laundry Bag x1",
        "Rain Covers x 0",
        "Laptop & gear x 1",
        "Phone Charger x 1",
        "Charge Cord x 1",
        "Travel Btry Sm x 1",
        "Travel Btry Lrg x 0",
        "Wireless Buds x 1",
        "Switch & gear x 0",
        "Extension Cord x 1",
        "Gum x 1",
        "Snacks x 3",
        "Empty Bottle x 1",
        "Lifting Wraps x 1",
        "Wallet x 1",
        "Keys x 1",
        "Passport x 1",
        "Silicone Ring x 0",
        "Ring x 1",
        "Ring Bandit x 1",
        "Emgcy Cash x 300",
        "Notepad & Pen x 1",
        "Sharpie x 1",
        "H2O Proof Pouch x 0",
        "Rmv Swiss Knife x 1",
        "First Aid Kit x 0",
        "MTG Cards x 0",
        "MTG Playmat x 0",
        "Counters & Dice x 0",
  ],
  hikingHot: [
    "T-Shirt x 4",
    "Exercise Shirt x 2",
    "Polo x 0",
    "Long-Slvd Shirt x 0",
    "Sun-Shirt x 3",
    "Dress Shirt x 0",
    "Under Shirt x 0",
    "Pajama Shirt x 2",
    "Jacket x 1",
    "Rain Jacket x 0",
    "Suit Jacket x 0",
    "Ski Jacket x 0",
    "Tie x 0",
    "Mask x 1",
    "Bandana x 4",
    "Head Band x 1",
    "Regular Belt x 1",
    "Dress Belt x 0",
    "Hiking Belt x 1",
    "Shorts x 3",
    "Gym Shorts x 2",
    "Swimsuit x 1",
    "Hiking Pants x 1",
    "Jeans x 1",
    "Dress Pants x 0",
    "Pajama Pants x 0",
    "Pajama Shorts x 1",
    "Waterproof Pants x 0",
    "Ski Pants x 0",
    "Briefs x 8",
    "Winter Undrwear x 0",
    "Short Socks x 9",
    "Long Socks x 0",
    "Winter Socks x 0",
    "Snapback x 1",
    "Trail Hat x 1",
    "Beanie x 0",
    "Snow Gloves x 0",
    "Reg Gloves x 0",
    "Scarf x 0",
    "Sneakers x 1",
    "Waterproof Boots x 0",
    "Reg Hiking Boots x 1",
    "Dress Shoes x 0",
    "Water Shoes x 0",
    "Sandals x 1",
    "Reg-Glasses x 1",
    "Sunglasses x 1",
    "Lense Cleaner x 1",
    "Eye Drops x 1",
    "Toothpaste x 1",
    "Toothbrush x 1",
    "Floss Sticks x 10",
    "Meds x 1",
    "Inhaler x 1",
    "vitamins x 1",
    "Sunscreen x 2",
    "Lotion x 1",
    "Hand Sanitizer x 1",
    "Clorox Trvl x 1",
    "Body Wash x 1",
    "Shampoo x 1",
    "Face Cleaner x 1",
    "Chapstick x 2",
    "Comb x 0",
    "Hair Putty x 0",
    "Deodorant x 1",
    "Shaving Kit x 0",
    "Tissues x 2",
    "Lint Roller x 0",
    "Shoe Shine x 0",
    "Bug Spray x 1",
    "Talcum Powder x 1",
    "Misc BR Items x 1",
    "Travel Towel x 1",
    "Travel Pillow x 1",
    "Hiking Bag x 1",
    "Sling Bag x 0",
    "Laundry Bag x 1",
    "Rain Covers x 0",
    "Laptop & gear x 0",
    "Phone Charger x 1",
    "Charge Cord x 1",
    "Travel Btry Sm x 1",
    "Travel Btry Lrg x 0",
    "Wireless Buds x 1",
    "Switch & gear x 0",
    "Extension Cord x 1",
    "Gum x 1",
    "Snacks x 6",
    "Empty Bottle x 1",
    "Lifting Wraps x 0",
    "Wallet x 1",
    "Keys x 1",
    "Passport x 0",
    "Silicone Ring x 1",
    "Ring x 0",
    "Ring Bandit x 1",
    "Emgcy Cash x 200",
    "Notepad & Pen x 1",
    "Sharpie x 1",
    "H2O Proof Pouch x 1",
    "Rmv Swiss Knife x 1",
    "First Aid Kit x 1",
    "MTG Cards x 0",
    "MTG Playmat x 0",
    "Counters & Dice x 0",
  ],
  beachTrip: [
    "T-Shirt x 3",
    "Exercise Shirt x 1",
    "Polo x 2",
    "Long-Slvd Shirt x 0",
    "Sun-Shirt x 2",
    "Dress Shirt x 0",
    "Under Shirt x 0",
    "Pajama Shirt x 1",
    "Jacket x 1",
    "Rain Jacket x 1",
    "Suit Jacket x 0",
    "Ski Jacket x 0",
    "Tie x 0",
    "Mask x 1",
    "Bandana x 4",
    "Head Band x 1",
    "Regular Belt x 1",
    "Dress Belt x 0",
    "Hiking Belt x 1",
    "Shorts x 4",
    "Gym Shorts x 1",
    "Swimsuit x 1",
    "Hiking Pants x 0",
    "Jeans x 2",
    "Dress Pants x 0",
    "Pajama Pants x 0",
    "Pajama Shorts x 1",
    "Waterproof Pants x 1",
    "Ski Pants x 0",
    "Briefs x 8",
    "Winter Undrwear x 0",
    "Short Socks x 7",
    "Long Socks x 0",
    "Winter Socks x 0",
    "Snapback x 1",
    "Trail Hat x 0",
    "Beanie x 0",
    "Snow Gloves x 0",
    "Reg Gloves x 0",
    "Scarf x 0",
    "Sneakers x 1",
    "Waterproof Boots x 0",
    "Reg Hiking Boots x 0",
    "Dress Shoes x 0",
    "Water Shoes x 1",
    "Sandals x 1",
    "Reg-Glasses x 1",
    "Sunglasses x 1",
    "Lense Cleaner x 1",
    "Eye Drops x 1",
    "Toothpaste x 1",
    "Toothbrush x 1",
    "Floss Sticks x 10",
    "Meds x 1",
    "Inhaler x 1",
    "vitamins x 1",
    "Sunscreen x 2",
    "Lotion x 1",
    "Hand Sanitizer x 1",
    "Clorox Trvl x 1",
    "Body Wash x 1",
    "Shampoo x 1",
    "Face Cleaner x 1",
    "Chapstick x 2",
    "Comb x 1",
    "Hair Putty x 1",
    "Deodorant x 1",
    "Shaving Kit x 0",
    "Tissues x 2",
    "Lint Roller x 0",
    "Shoe Shine x 0",
    "Bug Spray x 1",
    "Talcum Powder x 2",
    "Misc BR Items x 1",
    "Travel Towel x 1",
    "Travel Pillow x 1",
    "Hiking Bag x 1",
    "Sling Bag x 0",
    "Laundry Bag x 1",
    "Rain Covers x 0",
    "Laptop & gear x 0",
    "Phone Charger x 1",
    "Charge Cord x 1",
    "Travel Btry Sm x 1",
    "Travel Btry Lrg x 1",
    "Wireless Buds x 1",
    "Switch & gear x 0",
    "Extension Cord x 1",
    "Gum x 1",
    "Snacks x 4",
    "Empty Bottle x 1",
    "Lifting Wraps x 1",
    "Wallet x 1",
    "Keys x 1",
    "Passport x 0",
    "Silicone Ring x 1",
    "Ring x 0",
    "Ring Bandit x 1",
    "Emgcy Cash x 300",
    "Notepad & Pen x 1",
    "Sharpie x 1",
    "H2O Proof Pouch x 1",
    "Rmv Swiss Knife x 1",
    "First Aid Kit x 1",
    "MTG Cards x 0",
    "MTG Playmat x 0",
    "Counters & Dice x 0","T-Shirt x 3",
    "Exercise Shirt x 1",
    "Polo x 2",
    "Long-Slvd Shirt x 0",
    "Sun-Shirt x 2",
    "Dress Shirt x 0",
    "Under Shirt x 0",
    "Pajama Shirt x 1",
    "Jacket x 1",
    "Rain Jacket x 1",
    "Suit Jacket x 0",
    "Ski Jacket x 0",
    "Tie x 0",
    "Mask x 1",
    "Bandana x 4",
    "Head Band x 1",
    "Regular Belt x 1",
    "Dress Belt x 0",
    "Hiking Belt x 1",
    "Shorts x 4",
    "Gym Shorts x 1",
    "Swimsuit x 1",
    "Hiking Pants x 0",
    "Jeans x 2",
    "Dress Pants x 0",
    "Pajama Pants x 0",
    "Pajama Shorts x 1",
    "Waterproof Pants x 1",
    "Ski Pants x 0",
    "Briefs x 8",
    "Winter Undrwear x 0",
    "Short Socks x 7",
    "Long Socks x 0",
    "Winter Socks x 0",
    "Snapback x 1",
    "Trail Hat x 0",
    "Beanie x 0",
    "Snow Gloves x 0",
    "Reg Gloves x 0",
    "Scarf x 0",
    "Sneakers x 1",
    "Waterproof Boots x 0",
    "Reg Hiking Boots x 0",
    "Dress Shoes x 0",
    "Water Shoes x 1",
    "Sandals x 1",
    "Reg-Glasses x 1",
    "Sunglasses x 1",
    "Lense Cleaner x 1",
    "Eye Drops x 1",
    "Toothpaste x 1",
    "Toothbrush x 1",
    "Floss Sticks x 10",
    "Meds x 1",
    "Inhaler x 1",
    "vitamins x 1",
    "Sunscreen x 2",
    "Lotion x 1",
    "Hand Sanitizer x 1",
    "Clorox Trvl x 1",
    "Body Wash x 1",
    "Shampoo x 1",
    "Face Cleaner x 1",
    "Chapstick x 2",
    "Comb x 1",
    "Hair Putty x 1",
    "Deodorant x 1",
    "Shaving Kit x 0",
    "Tissues x 2",
    "Lint Roller x 0",
    "Shoe Shine x 0",
    "Bug Spray x 1",
    "Talcum Powder x 2",
    "Misc BR Items x 1",
    "Travel Towel x 1",
    "Travel Pillow x 1",
    "Hiking Bag x 1",
    "Sling Bag x 0",
    "Laundry Bag x 1",
    "Rain Covers x 0",
    "Laptop & gear x 0",
    "Phone Charger x 1",
    "Charge Cord x 1",
    "Travel Btry Sm x 1",
    "Travel Btry Lrg x 1",
    "Wireless Buds x 1",
    "Switch & gear x 0",
    "Extension Cord x 1",
    "Gum x 1",
    "Snacks x 4",
    "Empty Bottle x 1",
    "Lifting Wraps x 1",
    "Wallet x 1",
    "Keys x 1",
    "Passport x 0",
    "Silicone Ring x 1",
    "Ring x 0",
    "Ring Bandit x 1",
    "Emgcy Cash x 300",
    "Notepad & Pen x 1",
    "Sharpie x 1",
    "H2O Proof Pouch x 1",
    "Rmv Swiss Knife x 1",
    "First Aid Kit x 1",
    "MTG Cards x 0",
    "MTG Playmat x 0",
    "Counters & Dice x 0",
  ],
  museumCity: [
    "T-Shirt x 3",
        "Exercise Shirt x 1",
        "Polo x 2",
        "Long-Slvd Shirt x 1",
        "Sun-Shirt x 1",
        "Dress Shirt x 1",
        "Under Shirt x 1",
        "Pajama Shirt x 1",
        "Jacket x 1",
        "Rain Jacket x 0",
        "Suit Jacket x 0",
        "Ski Jacket x 0",
        "Tie x 0",
        "Mask x 1",
        "Bandana x 3",
        "Head Band x 1",
        "Regular Belt x 1",
        "Dress Belt x 1",
        "Hiking Belt x 1",
        "Shorts x 2",
        "Gym Shorts x 1",
        "Swimsuit x 0",
        "Hiking Pants x 2",
        "Jeans x 1",
        "Dress Pants x 1",
        "Pajama Pants x 0",
        "Pajama Shorts x 1",
        "Waterproof Pants x 0",
        "Ski Pants x 0",
        "Briefs x 7",
        "Winter Undrwear x 0",
        "Short Socks x 7",
        "Long Socks x 1",
        "Winter Socks x 0",
        "Snapback x 1",
        "Trail Hat x 0",
        "Beanie x 0",
        "Snow Gloves x 0",
        "Reg Gloves x 0",
        "Scarf x 0",
        "Sneakers x 1",
        "Waterproof Boots x 0",
        "Reg Hiking Boots x 0",
        "Dress Shoes x 1",
        "Water Shoes x 0",
        "Sandals x 1",
        "Reg-Glasses x 1",
        "Sunglasses x 1",
        "Lense Cleaner x 1",
        "Eye Drops x 1",
        "Toothpaste x 1",
        "Toothbrush x 1",
        "Floss Sticks x 10",
        "Meds x 1",
        "Inhaler x 1",
        "vitamins x 1",
        "Sunscreen x 1",
        "Lotion x 1",
        "Hand Sanitizer x 1",
        "Clorox Trvl x 1",
        "Body Wash x 1",
        "Shampoo x 1",
        "Face Cleaner x 1",
        "Chapstick x 2",
        "Comb x 1",
        "Hair Putty x 1",
        "Deodorant x 1",
        "Shaving Kit x 1",
        "Tissues x 2",
        "Lint Roller x 1",
        "Shoe Shine x 1",
        "Bug Spray x 1",
        "Talcum Powder x 1",
        "Misc BR Items x 1",
        "Travel Towel x 0",
        "Travel Pillow x 1",
        "Hiking Bag x 0",
        "Sling Bag x 1",
        "Laundry Bag x 1",
        "Rain Covers x 0",
        "Laptop & gear x 0",
        "Phone Charger x 1",
        "Charge Cord x 1",
        "Travel Btry Sm x 1",
        "Travel Btry Lrg x 0",
        "Wireless Buds x 1",
        "Switch & gear x 0",
        "Extension Cord x 1",
        "Gum x 1",
        "Snacks x 4",
        "Empty Bottle x 1",
        "Lifting Wraps x 0",
        "Wallet x 1",
        "Keys x 1",
        "Passport x 1",
        "Silicone Ring x 1",
        "Ring x 1",
        "Ring Bandit x 1",
        "Emgcy Cash x 300",
        "Notepad & Pen x 1",
        "Sharpie x 1",
        "H2O Proof Pouch x 0",
        "Rmv Swiss Knife x 1",
        "First Aid Kit x 0",
        "MTG Cards x 0",
        "MTG Playmat x 0",
        "Counters & Dice x 0",
  ],
  nerdTrip: [
    "T-Shirt x 6",
        "Exercise Shirt x 2",
        "Polo x 1",
        "Long-Slvd Shirt x 0",
        "Sun-Shirt x 1",
        "Dress Shirt x 0",
        "Under Shirt x 0",
        "Pajama Shirt x 2",
        "Jacket x 1",
        "Rain Jacket x 0",
        "Suit Jacket x 0",
        "Ski Jacket x 0",
        "Tie x 0",
        "Mask x 1",
        "Bandana x 4",
        "Head Band x 1",
        "Regular Belt x 1",
        "Dress Belt x 0",
        "Hiking Belt x 1",
        "Shorts x 4",
        "Gym Shorts x 2",
        "Swimsuit x 1",
        "Hiking Pants x 0",
        "Jeans x 2",
        "Dress Pants x 0",
        "Pajama Pants x 1",
        "Pajama Shorts x 1",
        "Waterproof Pants x 0",
        "Ski Pants x 0",
        "Briefs x 8",
        "Winter Undrwear x 0",
        "Short Socks x 7",
        "Long Socks x 1",
        "Winter Socks x 0",
        "Snapback x 1",
        "Trail Hat x 0",
        "Beanie x 0",
        "Snow Gloves x 0",
        "Reg Gloves x 0",
        "Scarf x 0",
        "Sneakers x 1",
        "Waterproof Boots x 0",
        "Reg Hiking Boots x 0",
        "Dress Shoes x 0",
        "Water Shoes x 0",
        "Sandals x 1",
        "Reg-Glasses x 1",
        "Sunglasses x 1",
        "Lense Cleaner x 1",
        "Eye Drops x 1",
        "Toothpaste x 1",
        "Toothbrush x 1",
        "Floss Sticks x 10",
        "Meds x 1",
        "Inhaler x 1",
        "vitamins x 1",
        "Sunscreen x 1",
        "Lotion x 1",
        "Hand Sanitizer x 1",
        "Clorox Trvl x 1",
        "Body Wash x 1",
        "Shampoo x 1",
        "Face Cleaner x 1",
        "Chapstick x 2",
        "Comb x 1",
        "Hair Putty x 1",
        "Deodorant x 1",
        "Shaving Kit x 0",
        "Tissues x 2",
        "Lint Roller x 0",
        "Shoe Shine x 0",
        "Bug Spray x 0",
        "Talcum Powder x 1",
        "Misc BR Items x 1",
        "Travel Towel x 1",
        "Travel Pillow x 1",
        "Hiking Bag x 1",
        "Sling Bag x 0",
        "Laundry Bag x 1",
        "Rain Covers x 0",
        "Laptop & gear x 1",
        "Phone Charger x 1",
        "Charge Cord x 1",
        "Travel Btry Sm x 0",
        "Travel Btry Lrg x 1",
        "Wireless Buds x 1",
        "Switch & gear x 1",
        "Extension Cord x 1",
        "Gum x 1",
        "Snacks x 4",
        "Empty Bottle x 1",
        "Lifting Wraps x 1",
        "Wallet x 1",
        "Keys x 1",
        "Passport x 0",
        "Silicone Ring x 1",
        "Ring x 0",
        "Ring Bandit x 1",
        "Emgcy Cash x 200",
        "Notepad & Pen x 1",
        "Sharpie x 1",
        "H2O Proof Pouch x 0",
        "Rmv Swiss Knife x 1",
        "First Aid Kit x 0",
        "MTG Cards x 1",
        "MTG Playmat x 1",
        "Counters & Dice x 1",
  ],
  skiTrip: [
    "T-Shirt x 3",
        "Exercise Shirt x 1",
        "Polo x 1",
        "Long-Slvd Shirt x 3",
        "Sun-Shirt x 1",
        "Dress Shirt x 0",
        "Under Shirt x 1",
        "Pajama Shirt x 1",
        "Jacket x 1",
        "Rain Jacket x 1",
        "Suit Jacket x 0",
        "Ski Jacket x 1",
        "Tie x 0",
        "Mask x 1",
        "Bandana x 4",
        "Head Band x 1",
        "Regular Belt x 1",
        "Dress Belt x 0",
        "Hiking Belt x 1",
        "Shorts x 0",
        "Gym Shorts x 0",
        "Swimsuit x 1",
        "Hiking Pants x 2",
        "Jeans x 2",
        "Dress Pants x 0",
        "Pajama Pants x 1",
        "Pajama Shorts x 0",
        "Waterproof Pants x 1",
        "Ski Pants x 1",
        "Briefs x 7",
        "Winter Undrwear x 2",
        "Short Socks x 2",
        "Long Socks x 3",
        "Winter Socks x 4",
        "Snapback x 1",
        "Trail Hat x 0",
        "Beanie x 1",
        "Snow Gloves x 1",
        "Reg Gloves x 1",
        "Scarf x 1",
        "Sneakers x 1",
        "Waterproof Boots x 1",
        "Reg Hiking Boots x 0",
        "Dress Shoes x 0",
        "Water Shoes x 0",
        "Sandals x 0",
        "Reg-Glasses x 1",
        "Sunglasses x 1",
        "Lense Cleaner x 1",
        "Eye Drops x 1",
        "Toothpaste x 1",
        "Toothbrush x 1",
        "Floss Sticks x 10",
        "Meds x 1",
        "Inhaler x 1",
        "vitamins x 1",
        "Sunscreen x 1",
        "Lotion x 1",
        "Hand Sanitizer x 1",
        "Clorox Trvl x 1",
        "Body Wash x 1",
        "Shampoo x 1",
        "Face Cleaner x 1",
        "Chapstick x 2",
        "Comb x 1",
        "Hair Putty x 0",
        "Deodorant x 1",
        "Shaving Kit x 0",
        "Tissues x 3",
        "Lint Roller x 0",
        "Shoe Shine x 0",
        "Bug Spray x 0",
        "Talcum Powder x 2",
        "Misc BR Items x 1",
        "Travel Towel x 1",
        "Travel Pillow x 1",
        "Hiking Bag x 1",
        "Sling Bag x 0",
        "Laundry Bag x 1",
        "Rain Covers x 2",
        "Laptop & gear x 0",
        "Phone Charger x 1",
        "Charge Cord x 1",
        "Travel Btry Sm x 1",
        "Travel Btry Lrg x 0",
        "Wireless Buds x 1",
        "Switch & gear x 0",
        "Extension Cord x 1",
        "Gum x 1",
        "Snacks x 4",
        "Empty Bottle x 1",
        "Lifting Wraps x 0",
        "Wallet x 1",
        "Keys x 1",
        "Passport x 0",
        "Silicone Ring x 1",
        "Ring x 0",
        "Ring Bandit x 1",
        "Emgcy Cash x 300",
        "Notepad & Pen x 1",
        "Sharpie x 1",
        "H2O Proof Pouch x 1",
        "Rmv Swiss Knife x 1",
        "First Aid Kit x 1",
        "MTG Cards x 0",
        "MTG Playmat x 0",
        "Counters & Dice x 0",
  ],
  tbd: [
    "T-Shirt x ",
        "Exercise Shirt x ",
        "Polo x ",
        "Long-Slvd Shirt x ",
        "Sun-Shirt x ",
        "Dress Shirt x ",
        "Under Shirt x ",
        "Pajama Shirt x ",
        "Jacket x ",
        "Rain Jacket x ",
        "Suit Jacket x ",
        "Ski Jacket x ",
        "Tie x ",
        "Mask x ",
        "Bandana x ",
        "Head Band x ",
        "Regular Belt x ",
        "Dress Belt x ",
        "Hiking Belt x ",
        "Shorts x ",
        "Gym Shorts x ",
        "Swimsuit x ",
        "Hiking Pants x ",
        "Jeans x ",
        "Dress Pants x ",
        "Pajama Pants x ",
        "Pajama Shorts x ",
        "Waterproof Pants x ",
        "Ski Pants x ",
        "Briefs x ",
        "Winter Undrwear x ",
        "Short Socks x ",
        "Long Socks x ",
        "Winter Socks x ",
        "Snapback x ",
        "Trail Hat x ",
        "Beanie x ",
        "Snow Gloves x ",
        "Reg Gloves x ",
        "Scarf x ",
        "Sneakers x ",
        "Waterproof Boots x ",
        "Reg Hiking Boots x ",
        "Dress Shoes x ",
        "Water Shoes x ",
        "Sandals x ",
        "Reg-Glasses x ",
        "Sunglasses x ",
        "Lense Cleaner x ",
        "Eye Drops x 1",
        "Toothpaste x ",
        "Toothbrush x ",
        "Floss Sticks x ",
        "Meds x ",
        "Inhaler x ",
        "vitamins x ",
        "Sunscreen x ",
        "Lotion x ",
        "Hand Sanitizer x ",
        "Clorox Trvl x ",
        "Body Wash x ",
        "Shampoo x ",
        "Face Cleaner x ",
        "Chapstick x ",
        "Comb x ",
        "Hair Putty x ",
        "Deodorant x ",
        "Shaving Kit x ",
        "Tissues x ",
        "Lint Roller x ",
        "Shoe Shine x ",
        "Bug Spray x ",
        "Talcum Powder x ",
        "Misc BR Items x ",
        "Travel Towel x ",
        "Travel Pillow x ",
        "Hiking Bag x ",
        "Sling Bag x ",
        "Laundry Bag x ",
        "Rain Covers x ",
        "Laptop & gear x ",
        "Phone Charger x ",
        "Charge Cord x ",
        "Travel Btry Sm x ",
        "Travel Btry Lrg x ",
        "Wireless Buds x ",
        "Switch & gear x ",
        "Extension Cord x ",
        "Gum x ",
        "Snacks x ",
        "Empty Bottle x ",
        "Lifting Wraps x ",
        "Wallet x ",
        "Keys x ",
        "Passport x ",
        "Silicone Ring x ",
        "Ring x ",
        "Ring Bandit x ",
        "Emgcy Cash x ",
        "Notepad & Pen x ",
        "Sharpie x ",
        "H2O Proof Pouch x ",
        "Rmv Swiss Knife x ",
        "First Aid Kit x ",
        "MTG Cards x ",
        "MTG Playmat x ",
        "Counters & Dice x ",
  ],
};


//TODO: add remaining packing lists